### ISSUE TITLE
在linux编译错误

### ISSUE THREAD

**Issue by ntlf9t** [xuehyc/XCore#46]
### Description

编译环境
debian11

xx@debian:~$ clang --version
Debian clang version 11.0.1-2

xx@debian:~$ cmake --version
cmake version 3.18.4

xx@debian:~$ dpkg -S /usr/include/boost/version.hpp
libboost1.74-dev:amd64: /usr/include/boost/version.hpp

xx@debian:~$ mariadb --version
mariadb  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

错误日志

In file included from <built-in>:1:
In file included from /home/xx/XCore/build/src/server/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
/home/xx/XCore/src/server/game/PrecompiledHeaders/gamePCH.h:24:10: fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/Maps/Map.h', but encoding is not supported
#include "Map.h"
         ^
1 error generated.

In file included from <built-in>:1:
In file included from /home/xx/XCore/build/src/server/game/CMakeFiles/game.dir/cmake_pch.hxx:5:
In file included from /home/xx/XCore/src/server/game/PrecompiledHeaders/gamePCH.h:28:
/home/xx/XCore/src/server/game/Entities/Player/Player.h:3019:106: error: redefinition of 'BoundInstancesMap'
        typedef std::unordered_map<Difficulty, std::unordered_map<uint32 /*mapId*/, InstancePlayerBind>> BoundInstancesMap;
                                                                                                         ^
/home/xx/XCore/src/server/game/Entities/Player/Player.h:2639:106: note: previous definition is here
        typedef std::unordered_map<Difficulty, std::unordered_map<uint32 /*mapId*/, InstancePlayerBind>> BoundInstancesMap;
                                                                                                         ^
1 error generated.

fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/AI/PlayerAI/BotAI.cpp', but encoding is not supported
1 error generated.

/home/xx/XCore/src/server/game/AI/PlayerAI/BotAITool.h:14:10: fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/Phasing/PhasingHandler.h', but encoding is not supported
#include "PhasingHandler.h"
         ^
1 error generated.

In file included from /home/xx/XCore/src/server/game/AI/PlayerAI/BotAI.cpp:33:
/home/xx/XCore/src/server/game/Server/Packets/MiscPackets.h:37:10: fatal error: 'Server\Packets\InspectPackets.h' file not found
#include <Server\Packets\InspectPackets.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/game/AI/PlayerAI/BotAI.cpp:40:10: fatal error: 'Battlegrounds\Battleground.h' file not found
#include <Battlegrounds\Battleground.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/AI/ScriptedAI/ScriptedGossip.cpp', but encoding is not supported
1 error generated.

In file included from /home/xx/XCore/src/server/game/AI/ScriptedAI/ScriptedGossip.cpp:18:
/home/xx/XCore/src/server/game/AI/ScriptedAI/ScriptedGossip.h:22:10: fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/Entities/Creature/GossipDef.h', but encoding is not supported
#include "GossipDef.h"
         ^
1 error generated.

fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/Accounts/BattlenetAccountMgr.cpp', but encoding is not supported
1 error generated.

/home/xx/XCore/src/server/game/Achievements/CriteriaHandler.cpp:38:10: fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/game/Maps/MapManager.h', but encoding is not supported
#include "MapManager.h"
         ^
1 error generated.

/home/xx/XCore/src/server/game/Entities/Player/Player.cpp:140:10: fatal error: '..\Custom\DynamicResurrection\DynamicResurrection.h' file not found
#include "..\Custom\DynamicResurrection\DynamicResurrection.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

/home/xx/XCore/src/server/game/Server/Packets/MiscPackets.cpp:22:10: fatal error: 'Time.h' file not found
#include "Time.h"
         ^~~~~~~~
1 error generated.

fatal error: UTF-16 (LE) byte order mark detected in '/home/xx/XCore/src/server/scripts/Custom/custom_script_loader.cpp', but encoding is not supported
1 error generated.

/home/xx/XCore/src/server/scripts/Custom/duelrest.cpp:3:10: fatal error: 'chat.h' file not found
#include "chat.h"
         ^~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Custom/login_reset.cpp:3:10: fatal error: 'world.h' file not found
#include "world.h"              //后加的库,必须
         ^~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Custom/npc_8000000_guardianangel.cpp:26:10: fatal error: 'wtypes.h' file not found
#include <wtypes.h>
         ^~~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Draenor/Auchindoun/boss_nyami.cpp:6:10: fatal error: 'G3D\Vector3.h' file not found
#include "G3D\Vector3.h"
         ^~~~~~~~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Kalimdor/ashenvale/ashenvale.cpp:30:10: fatal error: 'scriptPCH.h' file not found
#include "scriptPCH.h"
         ^~~~~~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Kalimdor/azshara/azshara.cpp:30:10: fatal error: 'scriptPCH.h' file not found
#include "scriptPCH.h"
         ^~~~~~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Kalimdor/winterspring/winterspring.cpp:30:10: fatal error: 'scriptPCH.h' file not found
#include "scriptPCH.h"
         ^~~~~~~~~~~~~
1 error generated.

/home/xx/XCore/src/server/scripts/Zandalar/zone_nazmir.cpp:54:44: error: no matching conversion for functional-style cast from 'Quests' to 'QuestObjective'
        if (!player->GetQuestObjectiveData(QuestObjective(QUEST_ITS_ALIVE)))
                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xx/XCore/src/server/game/Quests/QuestDef.h:393:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Quests' to 'const QuestObjective' for 1st argument
struct QuestObjective
       ^
/home/xx/XCore/src/server/game/Quests/QuestDef.h:393:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'Quests' to 'QuestObjective' for 1st argument
/home/xx/XCore/src/server/game/Quests/QuestDef.h:393:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
/home/xx/XCore/src/server/scripts/Zandalar/zone_nazmir.cpp:63:85: error: no matching conversion for functional-style cast from 'Quests' to 'QuestObjective'
        if (player->HasQuest(QUEST_PARTING_MISTS) && !player->GetQuestObjectiveData(QuestObjective(QUEST_PARTING_MISTS)))//,2
                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xx/XCore/src/server/game/Quests/QuestDef.h:393:8: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Quests' to 'const QuestObjective' for 1st argument
struct QuestObjective
       ^
/home/xx/XCore/src/server/game/Quests/QuestDef.h:393:8: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'Quests' to 'QuestObjective' for 1st argument
/home/xx/XCore/src/server/game/Quests/QuestDef.h:393:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
2 errors generated.

### Expected behaviour

需要修复脚本编码错误和头文件大小写错误

### Steps to reproduce the problem

参照第一步

### Branch

master

### TC rev. hash/commit

无

### Operating system

Debian 11 x64

### Custom changes

无

**Comment by xuehyc** [comment]
Linux下没试过,也可能是之前我上传时候有问题.可以在windows下试试,目前每次上传我都会测试编译通过再上传.

**Comment by ntlf9t** [comment]
其他我都修了，zone_nazmir.cpp修不出来直接注释了。运行了一下数据库报错用的是官方的TDB 1007.23041，原来用你上传的没问题[https://github.com/xuehyc/XCore/commit/3f257b8c754744e6e84d18da49f0660439781830](url)不过你删了没有新的了吗

**Comment by xuehyc** [comment]
有新的,没上传
